import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'

export const metadata: Metadata = {
  title: "Next.js Starter Kit",
  description: "Generated by create next app",
};

const aeonikFono = localFont({
  src: '../lib/fonts/aeonik-fono/AeonikFono-Regular.woff2'
})
const aeonikPro = localFont({
  src: '../lib/fonts/aeonik-pro/AeonikPro-Regular.woff2'
})

const firaCode = localFont({
  src: '../lib/fonts/fira-code/fira-code-latin-400-normal.woff2'
})

const inter = localFont({
  src: [
    {
      path: '../lib/fonts/inter/inter-latin-300-normal.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../lib/fonts/inter/inter-latin-400-normal.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../lib/fonts/inter/inter-latin-500-normal.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../lib/fonts/inter/inter-latin-600-normal.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../lib/fonts/inter/inter-latin-700-normal.woff2',
      weight: '700',
      style: 'normal',
    },
  ]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="dark mx-auto">
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
